services:
  teleferico:
    container_name: teleferico
    build: .
    ports:
      - 3333:3333
    env_file:
      - .env
    command: ['./command.sh']
    depends_on:
      - teleferico_db

  teleferico_db:
    container_name: teleferico_db
    image: postgis/postgis:17-3.4
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teleferico_db
    volumes:
      - pgdata_teleferico:/var/lib/postgresql/data

volumes:
  pgdata_teleferico:
