export const LINEAS_REPOSITORY = 'LINEAS_REPOSITORY'
export const ESTACIONES_REPOSITORY = 'ESTACIONES_REPOSITORY'
export const LINEA_ESTACION_REPOSITORY = 'LINEA_ESTACION_REPOSITORY'
export const POSTES_REPOSITORY = 'POSTES_REPOSITORY'
